[package]
name = "cynic-proc-macros"
version = "0.14.1"
authors = ["Graeme Coupar <graeme@polyandglot.dev>"]
edition = "2018"
homepage = "https://cynic-rs.dev"
repository = "https://github.com/obmarg/cynic"
description = "Procedural macro crate for cynic - a GraphQL query builder & data mapper for Rust"
license = "MPL-2.0"
documentation = "https://docs.rs/cynic-proc-macros"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
cynic-codegen = { path = "../cynic-codegen", version = "0.14.1" }
cynic-querygen = { path = "../cynic-querygen", version = "0.14.0" }
syn = "1.0.13"
cargo_toml = "0.9.2"
serde = { version = "1.0.126", features = ["derive"] }
graphql-parser = { path = "../../graphql-parser" }
ariadne = "0.1.2"
proc-macro2 = "1.0.28"
yansi = "0.5.0"
quote = "1.0.9"